### ISSUE TITLE
Criar um "card" de produtos com a tag article

### ISSUE THREAD

**Issue by fabriciofx** [pauloandreoliv/DSWI#1]
Devemos criar um "card" de produto para cada produto listado. Para isto, deve-se colocar a tag `<article>` em cada produto da página `produtos.html`.

**Comment by pauloandreoliv** [comment]
Tags adicionadas, por favor, verificar.

Done #1

**Comment by pauloandreoliv** [comment]
Tags inseridas, por favor, verificar.

**Comment by pauloandreoliv** [comment]
@fabriciofx

Tags inseridas, por favor, verificar.

**Comment by fabriciofx** [comment]
@pauloandreoliv ok!
